version: '3.8'

services:
  fastapi:
    build:
      context: src/.
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
  database:
    image: postgres
    env_file: ./src/.env.dev
    ports:
      - "5435:5435"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
