version: '3.8'

services:
  fastapi:
    build:
      context: src/.
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
  database:
    image: postgres
    env_file: ./src/.env.test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./test_init.sql:/docker-entrypoint-initdb.d/test_init.sql

volumes:
  database:
